import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const resend = new Resend(process.env.RESEND_API_KEY!);

export async function GET() {

    try {

        // ----------------------------------
        // DATE RANGE (Last week)
        // ----------------------------------

        const now = new Date();

        const start = new Date(now);
        start.setDate(now.getDate() - 7);

        const startISO = start.toISOString();
        const endISO = now.toISOString();

        // ----------------------------------
        // FETCH ORDERS
        // ----------------------------------

        const { data: orders } = await supabase
            .from("orders")
            .select("*")
            .gte("ordered_at", startISO)
            .lte("ordered_at", endISO);

        const { data: items } = await supabase
            .from("order_items")
            .select("*")
            .gte("created_at", startISO)
            .lte("created_at", endISO);

        // ----------------------------------
        // GLOBAL SUMMARY
        // ----------------------------------

        const totalOrders = orders?.length || 0;

        const totalAmount =
            orders?.reduce((sum, o) => sum + Number(o.price_paid || 0), 0) || 0;

        const totalSkus =
            items?.reduce((sum, i) => sum + i.quantity, 0) || 0;

        // ----------------------------------
        // STORE GROUPING
        // ----------------------------------

        const storeMap: any = {};

        orders?.forEach((order) => {

            const store = order.collection_handle || "Unknown";

            if (!storeMap[store]) {
                storeMap[store] = {
                    orders: [],
                    items: []
                };
            }

            storeMap[store].orders.push(order);

        });

        items?.forEach((item) => {

            const order = orders?.find(o => o.id === item.order_id);

            const store = order?.collection_handle || "Unknown";

            if (!storeMap[store]) {
                storeMap[store] = { orders: [], items: [] };
            }

            storeMap[store].items.push(item);

        });

        // ----------------------------------
        // BUILD HTML
        // ----------------------------------

        let storeSections = "";

        for (const store in storeMap) {

            const storeData = storeMap[store];

            const productMap: any = {};

            storeData.items.forEach((item: any) => {

                const key = `${item.product_name}-${item.size}`;

                if (!productMap[key]) {

                    productMap[key] = {
                        product: item.product_name,
                        size: item.size,
                        qty: 0
                    };

                }

                productMap[key].qty += item.quantity;

            });

            let rows = "";

            Object.values(productMap).forEach((p: any) => {

                rows += `
        <tr>
          <td>${p.product}</td>
          <td>${p.size}</td>
          <td>${p.qty}</td>
        </tr>
        `;

            });

            storeSections += `

      <h2 style="margin-top:40px">${store.toUpperCase()}</h2>

      <table style="width:100%;border-collapse:collapse;margin-top:10px">

        <thead>
          <tr style="background:#f4f4f4">
            <th style="padding:10px;text-align:left">Product</th>
            <th style="padding:10px;text-align:left">Size</th>
            <th style="padding:10px;text-align:left">Quantity</th>
          </tr>
        </thead>

        <tbody>
          ${rows}
        </tbody>

      </table>

      `;

        }

        // ----------------------------------
        // FINAL EMAIL HTML
        // ----------------------------------

        const html = `

    <div style="font-family:Arial;padding:40px;background:#fafafa">

      <h1 style="margin-bottom:10px">Weekly Store Summary</h1>

      <p style="color:#666">Automated report generated by AurixLab</p>

      <div style="display:flex;gap:40px;margin-top:30px">

        <div>
          <h3>Total Orders</h3>
          <p style="font-size:24px;font-weight:bold">${totalOrders}</p>
        </div>

        <div>
          <h3>Total Revenue</h3>
          <p style="font-size:24px;font-weight:bold">$${totalAmount.toFixed(2)}</p>
        </div>

        <div>
          <h3>Total Items</h3>
          <p style="font-size:24px;font-weight:bold">${totalSkus}</p>
        </div>

      </div>

      ${storeSections}

      <hr style="margin-top:60px"/>

      <p style="font-size:12px;color:#888">
        Sent by AurixLab Automation
      </p>

    </div>

    `;

        // ----------------------------------
        // SEND EMAIL
        // ----------------------------------
        console.log("📧 Sending weekly summary email...", html);
        const emailsent = await resend.emails.send({

            from: "AurixLab Automation <reports@aurixlab.com>",

            to: "mehrab367@gmail.com",

            subject: "Weekly Store Summary",

            html

        });
        console.log("📧 Weekly summary email sent:", emailsent);
        return NextResponse.json({ success: true });

    } catch (err) {

        console.error(err);

        return NextResponse.json({ error: "failed" });

    }

}